/**
 * 상세 분석 화면
 * V4 트렌디 UI
 */

import React from 'react';
import {
  View,
  Text,
  StyleSheet,
  ScrollView,
  TouchableOpacity,
  Alert,
} from 'react-native';
import {useFatigue} from '../contexts/FatigueContext';
import {ACTIVITY_TYPE_INFO} from '../utils/constants';
import {ActivityType, DataSource} from '../types';
import {useTheme} from '../contexts/ThemeContext';
import {COLORS, SHADOWS, SPACING, RADIUS, TYPOGRAPHY} from '../utils/theme';

interface DetailsScreenProps {
  navigation: any;
}

const DATA_SOURCE_LABELS: Record<string, string> = {
  [DataSource.APPLE_HEALTH]: 'Apple Health',
  [DataSource.GOOGLE_FIT]: 'Google Fit',
  [DataSource.SAMSUNG_HEALTH]: 'Samsung Health',
  [DataSource.PHONE_ESTIMATED]: '수면 추정',
  [DataSource.AUTO_SEDENTARY]: '자동 감지',
  [DataSource.MANUAL_ACTIVITY]: '수동',
  [DataSource.MANUAL_SLIDER]: '슬라이더',
  [DataSource.AUTO_IDLE_REST]: '유휴 회복',
  [DataSource.NOTIFICATION_ACTION]: '알림 액션',
};

const DetailsScreen: React.FC<DetailsScreenProps> = ({navigation}) => {
  const {colors, shadows} = useTheme();
  const {dailyData, removeActivity, clearAllActivities} = useFatigue();

  const handleDeleteActivity = (activityId: string, activityName: string) => {
    Alert.alert(
      '삭제 확인',
      `"${activityName}" 활동을 삭제하시겠습니까?`,
      [
        {text: '취소', style: 'cancel'},
        {
          text: '삭제',
          style: 'destructive',
          onPress: () => removeActivity(activityId),
        },
      ],
    );
  };

  const handleClearAll = () => {
    Alert.alert(
      '전체 삭제',
      '모든 활동을 삭제하시겠습니까? 이 작업은 되돌릴 수 없습니다.',
      [
        {text: '취소', style: 'cancel'},
        {
          text: '삭제',
          style: 'destructive',
          onPress: clearAllActivities,
        },
      ],
    );
  };

  const activitySummary = Object.values(ActivityType).map(type => {
    const activities = dailyData.activities.filter(a => a.type === type);
    const totalMinutes = activities.reduce((sum, a) => sum + a.durationMinutes, 0);
    const info = ACTIVITY_TYPE_INFO[type];

    return {
      type,
      info,
      totalMinutes,
      count: activities.length,
      activities,
    };
  }).filter(item => item.count > 0);

  const fatigueActivities = activitySummary.filter(item => !item.info.isRecovery);
  const recoveryActivities = activitySummary.filter(item => item.info.isRecovery);

  const formatDuration = (minutes: number) => {
    const hours = Math.floor(minutes / 60);
    const mins = minutes % 60;
    if (hours > 0) {
      return mins > 0 ? `${hours}시간 ${mins}분` : `${hours}시간`;
    }
    return `${mins}분`;
  };

  const formatTime = (date: Date) => {
    return new Date(date).toLocaleTimeString('ko-KR', {
      hour: '2-digit',
      minute: '2-digit',
    });
  };

  return (
    <ScrollView style={[styles.container, {backgroundColor: colors.background}]} showsVerticalScrollIndicator={false}>
      <View style={styles.content}>
        {/* 통계 헤더 */}
        <View style={styles.statsContainer}>
          <View style={[styles.statCard, {backgroundColor: colors.surface}, shadows.card]}>
            <Text style={[styles.statNumber, {color: colors.accent}]}>{dailyData.activities.length}</Text>
            <Text style={[styles.statLabel, {color: colors.textTertiary}]}>총 활동</Text>
          </View>
          <View style={[styles.statCard, {backgroundColor: colors.surface}, shadows.card]}>
            <Text style={[styles.statNumber, {color: colors.accent}]}>
              {dailyData.activities.filter(a => a.autoGenerated).length}
            </Text>
            <Text style={[styles.statLabel, {color: colors.textTertiary}]}>자동 기록</Text>
          </View>
          <View style={[styles.statCard, {backgroundColor: colors.surface}, shadows.card]}>
            <Text style={[styles.statNumber, {color: colors.accent}]}>
              {dailyData.activities.filter(a => !a.autoGenerated).length}
            </Text>
            <Text style={[styles.statLabel, {color: colors.textTertiary}]}>수동 기록</Text>
          </View>
        </View>

        {/* 피로 증가 활동 */}
        {fatigueActivities.length > 0 && (
          <View style={styles.section}>
            <Text style={[styles.sectionTitle, {color: colors.textPrimary}]}>피로 증가 활동</Text>
            {fatigueActivities.map(item => (
              <View key={item.type} style={[styles.activityTypeCard, {backgroundColor: colors.surface}, shadows.card]}>
                <View style={styles.activityTypeHeader}>
                  <View style={styles.activityTypeInfo}>
                    <Text style={styles.activityTypeEmoji}>{item.info.emoji}</Text>
                    <View>
                      <Text style={[styles.activityTypeName, {color: colors.textPrimary}]}>
                        {item.info.displayName}
                      </Text>
                      <Text style={[styles.activityTypeSummary, {color: colors.textSecondary}]}>
                        {formatDuration(item.totalMinutes)} • {item.count}회
                      </Text>
                    </View>
                  </View>
                </View>

                {item.activities.map(activity => (
                  <View key={activity.id} style={[styles.activityItem, {borderTopColor: colors.divider}]}>
                    <View style={styles.activityItemInfo}>
                      <View style={styles.activityTimeRow}>
                        <Text style={[styles.activityTime, {color: colors.textSecondary}]}>
                          {formatTime(activity.timestamp)}
                        </Text>
                        {activity.autoGenerated && (
                          <View style={[styles.autoBadge, {backgroundColor: colors.accentLight}]}>
                            <Text style={[styles.autoBadgeText, {color: colors.accent}]}>AUTO</Text>
                          </View>
                        )}
                        {activity.source && (
                          <Text style={[styles.sourceLabel, {color: colors.textTertiary}]}>
                            {DATA_SOURCE_LABELS[activity.source] ?? activity.source}
                          </Text>
                        )}
                      </View>
                      <Text style={[styles.activityDuration, {color: colors.textPrimary}]}>
                        {formatDuration(activity.durationMinutes)}
                      </Text>
                      {activity.note && (
                        <Text style={[styles.activityNote, {color: colors.textTertiary}]}>{activity.note}</Text>
                      )}
                    </View>
                    <TouchableOpacity
                      style={[styles.deleteButton, {backgroundColor: colors.fatigue.exhausted + '18'}]}
                      onPress={() =>
                        handleDeleteActivity(activity.id, item.info.displayName)
                      }
                      activeOpacity={0.7}>
                      <Text style={[styles.deleteButtonText, {color: colors.fatigue.exhausted}]}>삭제</Text>
                    </TouchableOpacity>
                  </View>
                ))}
              </View>
            ))}
          </View>
        )}

        {/* 회복 활동 */}
        {recoveryActivities.length > 0 && (
          <View style={styles.section}>
            <Text style={[styles.sectionTitle, {color: colors.textPrimary}]}>회복 활동</Text>
            {recoveryActivities.map(item => (
              <View key={item.type} style={[styles.activityTypeCard, {backgroundColor: colors.metricBg.sleep}, shadows.card]}>
                <View style={styles.activityTypeHeader}>
                  <View style={styles.activityTypeInfo}>
                    <Text style={styles.activityTypeEmoji}>{item.info.emoji}</Text>
                    <View>
                      <Text style={[styles.activityTypeName, {color: colors.textPrimary}]}>
                        {item.info.displayName}
                      </Text>
                      <Text style={[styles.activityTypeSummary, {color: colors.textSecondary}]}>
                        {formatDuration(item.totalMinutes)} • {item.count}회
                      </Text>
                    </View>
                  </View>
                </View>

                {item.activities.map(activity => (
                  <View key={activity.id} style={[styles.activityItem, {borderTopColor: colors.divider}]}>
                    <View style={styles.activityItemInfo}>
                      <View style={styles.activityTimeRow}>
                        <Text style={[styles.activityTime, {color: colors.textSecondary}]}>
                          {formatTime(activity.timestamp)}
                        </Text>
                        {activity.autoGenerated && (
                          <View style={[styles.autoBadge, {backgroundColor: colors.accentLight}]}>
                            <Text style={[styles.autoBadgeText, {color: colors.accent}]}>AUTO</Text>
                          </View>
                        )}
                        {activity.source && (
                          <Text style={[styles.sourceLabel, {color: colors.textTertiary}]}>
                            {DATA_SOURCE_LABELS[activity.source] ?? activity.source}
                          </Text>
                        )}
                      </View>
                      <Text style={[styles.activityDuration, {color: colors.textPrimary}]}>
                        {formatDuration(activity.durationMinutes)}
                      </Text>
                      {activity.note && (
                        <Text style={[styles.activityNote, {color: colors.textTertiary}]}>{activity.note}</Text>
                      )}
                    </View>
                    <TouchableOpacity
                      style={[styles.deleteButton, {backgroundColor: colors.fatigue.exhausted + '18'}]}
                      onPress={() =>
                        handleDeleteActivity(activity.id, item.info.displayName)
                      }
                      activeOpacity={0.7}>
                      <Text style={[styles.deleteButtonText, {color: colors.fatigue.exhausted}]}>삭제</Text>
                    </TouchableOpacity>
                  </View>
                ))}
              </View>
            ))}
          </View>
        )}

        {/* 활동 없음 */}
        {dailyData.activities.length === 0 && (
          <View style={styles.emptyContainer}>
            <Text style={styles.emptyEmoji}>📝</Text>
            <Text style={[styles.emptyText, {color: colors.textSecondary}]}>아직 기록된 활동이 없습니다</Text>
            <TouchableOpacity
              style={[styles.addButton, {backgroundColor: colors.accent}]}
              onPress={() => navigation.navigate('AddActivity')}
              activeOpacity={0.7}>
              <Text style={styles.addButtonText}>활동 추가하기</Text>
            </TouchableOpacity>
          </View>
        )}

        {/* 전체 삭제 버튼 */}
        {dailyData.activities.length > 0 && (
          <TouchableOpacity
            style={[styles.clearAllButton, {backgroundColor: colors.fatigue.exhausted + '18'}]}
            onPress={handleClearAll}
            activeOpacity={0.7}>
            <Text style={[styles.clearAllButtonText, {color: colors.fatigue.exhausted}]}>전체 삭제</Text>
          </TouchableOpacity>
        )}
      </View>
    </ScrollView>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.background,
  },
  content: {
    padding: SPACING.screenPadding,
    paddingBottom: 40,
  },
  statsContainer: {
    flexDirection: 'row',
    gap: 10,
    marginBottom: 28,
  },
  statCard: {
    flex: 1,
    backgroundColor: COLORS.surface,
    borderRadius: RADIUS.card,
    padding: 15,
    alignItems: 'center',
    ...SHADOWS.card,
  },
  statNumber: {
    fontSize: 28,
    fontWeight: 'bold',
    color: COLORS.accent,
  },
  statLabel: {
    ...TYPOGRAPHY.small,
    marginTop: 4,
  },
  section: {
    marginBottom: 28,
  },
  sectionTitle: {
    ...TYPOGRAPHY.heading,
    marginBottom: 14,
  },
  activityTypeCard: {
    backgroundColor: COLORS.surface,
    borderRadius: RADIUS.card,
    padding: 16,
    marginBottom: 12,
    ...SHADOWS.card,
  },
  recoveryCard: {
    backgroundColor: COLORS.metricBg.sleep,
  },
  activityTypeHeader: {
    marginBottom: 10,
  },
  activityTypeInfo: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  activityTypeEmoji: {
    fontSize: 28,
    marginRight: 14,
  },
  activityTypeName: {
    ...TYPOGRAPHY.heading,
  },
  activityTypeSummary: {
    ...TYPOGRAPHY.caption,
    marginTop: 2,
  },
  activityItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 10,
    borderTopWidth: 1,
    borderTopColor: COLORS.divider,
  },
  activityItemInfo: {
    flex: 1,
  },
  activityTimeRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  activityTime: {
    ...TYPOGRAPHY.caption,
  },
  autoBadge: {
    backgroundColor: COLORS.accentLight,
    borderRadius: 4,
    paddingHorizontal: 6,
    paddingVertical: 2,
  },
  autoBadgeText: {
    fontSize: 10,
    fontWeight: 'bold',
    color: COLORS.accent,
  },
  sourceLabel: {
    fontSize: 10,
    color: COLORS.textTertiary,
  },
  activityDuration: {
    fontSize: 16,
    fontWeight: '600',
    color: COLORS.textPrimary,
    marginTop: 2,
  },
  activityNote: {
    ...TYPOGRAPHY.caption,
    color: COLORS.textTertiary,
    marginTop: 4,
    fontStyle: 'italic',
  },
  deleteButton: {
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 8,
  },
  deleteButtonText: {
    color: COLORS.fatigue.exhausted,
    fontSize: 13,
    fontWeight: '600',
  },
  emptyContainer: {
    alignItems: 'center',
    paddingVertical: 60,
  },
  emptyEmoji: {
    fontSize: 56,
    marginBottom: 16,
  },
  emptyText: {
    ...TYPOGRAPHY.heading,
    color: COLORS.textSecondary,
    marginBottom: 24,
  },
  addButton: {
    backgroundColor: COLORS.accent,
    paddingHorizontal: 30,
    paddingVertical: 15,
    borderRadius: RADIUS.small,
  },
  addButtonText: {
    color: COLORS.white,
    fontSize: 16,
    fontWeight: 'bold',
  },
  clearAllButton: {
    paddingVertical: 15,
    borderRadius: RADIUS.small,
    alignItems: 'center',
    marginTop: 10,
  },
  clearAllButtonText: {
    color: COLORS.fatigue.exhausted,
    fontSize: 16,
    fontWeight: '600',
  },
});

export default DetailsScreen;
