/**
 * 피로도 앱 타입 정의
 */

/**
 * 활동 유형
 */
export enum ActivityType {
  // 피로 증가 요소
  WORK = 'WORK',
  SCREEN_TIME = 'SCREEN_TIME',
  SITTING = 'SITTING',
  STRESS = 'STRESS',
  CAFFEINE = 'CAFFEINE',

  // 회복 요소
  SLEEP = 'SLEEP',
  EXERCISE = 'EXERCISE',
  REST = 'REST',
  OUTDOOR = 'OUTDOOR',
  WATER = 'WATER',
  MEAL = 'MEAL',
}

/**
 * 활동 타입 메타데이터
 */
export interface ActivityTypeInfo {
  type: ActivityType;
  displayName: string;
  emoji: string;
  fatigueWeight: number; // 피로도 가중치 (-는 회복, +는 피로)
  isRecovery: boolean;
}

/**
 * 입력 모드 (3단계 티어)
 */
export enum InputMode {
  WATCH = 'WATCH',     // Tier A: 스마트워치
  PHONE = 'PHONE',     // Tier B: 폰 센서만
  MANUAL = 'MANUAL',   // Tier C: 간편 슬라이더
}

/**
 * 데이터 소스 추적
 */
export enum DataSource {
  APPLE_HEALTH = 'APPLE_HEALTH',
  GOOGLE_FIT = 'GOOGLE_FIT',
  SAMSUNG_HEALTH = 'SAMSUNG_HEALTH',
  PHONE_SENSOR = 'PHONE_SENSOR',
  PHONE_ESTIMATED = 'PHONE_ESTIMATED',
  MANUAL_SLIDER = 'MANUAL_SLIDER',
  MANUAL_ACTIVITY = 'MANUAL_ACTIVITY',
  AUTO_SEDENTARY = 'AUTO_SEDENTARY',
  AUTO_IDLE_REST = 'AUTO_IDLE_REST',
  NOTIFICATION_ACTION = 'NOTIFICATION_ACTION',
}

/**
 * 활동 기록
 */
export interface ActivityRecord {
  id: string;
  type: ActivityType;
  durationMinutes: number;
  timestamp: Date;
  note?: string;
  source?: DataSource;
  autoGenerated?: boolean;
}

/**
 * 수면 데이터
 */
export interface SleepData {
  totalMinutes: number;
  deepMinutes?: number;
  lightMinutes?: number;
  remMinutes?: number;
  awakeMinutes?: number;
  source: DataSource;
}

/**
 * 건강 데이터 스냅샷
 */
export interface HealthDataSnapshot {
  timestamp: Date;
  source: DataSource;
  heartRate?: number;
  heartRateVariability?: number;
  stressLevel?: number;
  sleepData?: SleepData;
  stepCount?: number;
  screenTimeMinutes?: number;
  estimatedSleepData?: SleepData;
  sedentaryMinutes?: number;
}

/**
 * 앉아있기 감지 이벤트
 */
export interface SedentaryEvent {
  startTime: Date;
  endTime: Date;
  durationMinutes: number;
  autoDetected: boolean;
}

/**
 * 앱 설정
 */
export interface AppSettings {
  inputMode: InputMode;
  enableSedentaryDetection: boolean;
  sedentaryThresholdMinutes: number;
  enableNotifications: boolean;
  daytimeStartHour: number;
  daytimeEndHour: number;
  onboardingComplete: boolean;
}

/**
 * 피로도 레벨
 */
export enum FatigueLevel {
  EXCELLENT = 'EXCELLENT',
  GOOD = 'GOOD',
  TIRED = 'TIRED',
  EXHAUSTED = 'EXHAUSTED',
}

/**
 * 피로도 레벨 정보
 */
export interface FatigueLevelInfo {
  level: FatigueLevel;
  range: [number, number];
  displayName: string;
  emoji: string;
  color: string;
  message: string;
}

/**
 * 일일 피로도 데이터
 */
export interface DailyFatigueData {
  date: string;
  activities: ActivityRecord[];
  currentFatiguePercentage: number;
  notes?: string;
  healthSnapshots?: HealthDataSnapshot[];
  sedentaryEvents?: SedentaryEvent[];
  manualSliderValue?: number;
  inputMode?: InputMode;
}

/**
 * 피로도 통계
 */
export interface FatigueStats {
  totalActivities: number;
  totalFatigueImpact: number;
  activityContributions: Map<ActivityType, number>;
  recommendation: string;
  fatigueMessage: string;
}

/**
 * 일별 히스토리 레코드 (차트용)
 */
export interface DailyHistoryRecord {
  date: string;
  fatiguePercentage: number;
  stepCount: number;
  sleepHours: number;
  activityCount: number;
}

/**
 * 회복 추천 팁
 */
export interface RecoveryTip {
  emoji: string;
  title: string;
  description: string;
  priority: number;
  action?: RecoveryAction;
}

export interface RecoveryAction {
  label: string;
  type: 'timer' | 'quick_add' | 'link';
  timerMinutes?: number;
  activityType?: ActivityType;
  activityDuration?: number;
}
