/**
 * 피로도 앱 타입 정의
 */

/**
 * 활동 유형
 */
export enum ActivityType {
  // 피로 증가 요소
  WORK = 'WORK',
  SCREEN_TIME = 'SCREEN_TIME',
  SITTING = 'SITTING',
  STRESS = 'STRESS',
  CAFFEINE = 'CAFFEINE',

  // 회복 요소
  SLEEP = 'SLEEP',
  EXERCISE = 'EXERCISE',
  REST = 'REST',
  OUTDOOR = 'OUTDOOR',
  WATER = 'WATER',
  MEAL = 'MEAL',
}

/**
 * 활동 타입 메타데이터
 */
export interface ActivityTypeInfo {
  type: ActivityType;
  displayName: string;
  emoji: string;
  fatigueWeight: number; // 피로도 가중치 (-는 회복, +는 피로)
  isRecovery: boolean;
}

/**
 * 입력 모드
 */
export enum InputMode {
  AUTO = 'AUTO',       // 자동: 워치+폰 건강 데이터 통합
  MANUAL = 'MANUAL',   // 수동: 간편 슬라이더
}

/**
 * 데이터 소스 추적
 */
export enum DataSource {
  APPLE_HEALTH = 'APPLE_HEALTH',
  GOOGLE_FIT = 'GOOGLE_FIT',
  SAMSUNG_HEALTH = 'SAMSUNG_HEALTH',
  PHONE_ESTIMATED = 'PHONE_ESTIMATED',
  MANUAL_SLIDER = 'MANUAL_SLIDER',
  MANUAL_ACTIVITY = 'MANUAL_ACTIVITY',
  AUTO_SEDENTARY = 'AUTO_SEDENTARY',
  AUTO_IDLE_REST = 'AUTO_IDLE_REST',
  NOTIFICATION_ACTION = 'NOTIFICATION_ACTION',
}

/**
 * 활동 기록
 */
export interface ActivityRecord {
  id: string;
  type: ActivityType;
  durationMinutes: number;
  timestamp: Date;
  note?: string;
  source?: DataSource;
  autoGenerated?: boolean;
}

/**
 * 수면 데이터
 */
export interface SleepData {
  totalMinutes: number;
  deepMinutes?: number;
  lightMinutes?: number;
  remMinutes?: number;
  awakeMinutes?: number;
  source: DataSource;
}

/**
 * 건강 데이터 스냅샷
 */
export interface HealthDataSnapshot {
  timestamp: Date;
  source: DataSource;
  heartRate?: number;
  heartRateVariability?: number;
  stressLevel?: number;
  sleepData?: SleepData;
  stepCount?: number;
  screenTimeMinutes?: number;
  estimatedSleepData?: SleepData;
  sedentaryMinutes?: number;
}

/**
 * 앉아있기 감지 이벤트
 */
export interface SedentaryEvent {
  startTime: Date;
  endTime: Date;
  durationMinutes: number;
  autoDetected: boolean;
}

/**
 * 앱 설정
 */
export interface AppSettings {
  inputMode: InputMode;
  enableSedentaryDetection: boolean;
  sedentaryThresholdMinutes: number;
  enableNotifications: boolean;
  daytimeStartHour: number;
  daytimeEndHour: number;
  onboardingComplete: boolean;
}

/**
 * 피로도 레벨
 */
export enum FatigueLevel {
  EXCELLENT = 'EXCELLENT',
  GOOD = 'GOOD',
  TIRED = 'TIRED',
  EXHAUSTED = 'EXHAUSTED',
}

/**
 * 피로도 레벨 정보
 */
export interface FatigueLevelInfo {
  level: FatigueLevel;
  range: [number, number];
  displayName: string;
  emoji: string;
  color: string;
  message: string;
}

/**
 * 일일 피로도 데이터
 */
export interface DailyFatigueData {
  date: string;
  activities: ActivityRecord[];
  currentFatiguePercentage: number;
  notes?: string;
  healthSnapshots?: HealthDataSnapshot[];
  sedentaryEvents?: SedentaryEvent[];
  manualSliderValue?: number;
  inputMode?: InputMode;
}

/**
 * 피로도 통계
 */
export interface FatigueStats {
  totalActivities: number;
  totalFatigueImpact: number;
  activityContributions: Map<ActivityType, number>;
  recommendation: string;
  fatigueMessage: string;
}

/**
 * 일별 히스토리 레코드 (차트용)
 */
export interface DailyHistoryRecord {
  date: string;
  fatiguePercentage: number;
  stepCount: number;
  sleepHours: number;
  activityCount: number;
}

/**
 * 회복 추천 팁
 */
export interface RecoveryTip {
  emoji: string;
  title: string;
  description: string;
  priority: number;
  action?: RecoveryAction;
}

export interface RecoveryAction {
  label: string;
  type: 'timer' | 'quick_add' | 'link';
  timerMinutes?: number;
  activityType?: ActivityType;
  activityDuration?: number;
}

// ============================================================
// 뿜(PPOOM) 캐릭터 & 미션 시스템
// ============================================================

/**
 * 뿜 캐릭터 상태 (피로도 기반)
 */
export enum PpoomState {
  CHARGED = 'CHARGED',       // 0-20%: 충전 완료
  GOOD = 'GOOD',             // 20-40%: 좋음
  NORMAL = 'NORMAL',         // 40-60%: 보통
  TIRED = 'TIRED',           // 60-80%: 피곤
  DISCHARGED = 'DISCHARGED', // 80-100%: 방전
}

/**
 * 미션 카테고리
 */
export enum MissionCategory {
  WATER = 'WATER',
  ACTIVITY = 'ACTIVITY',
  SLEEP = 'SLEEP',
  FOOD = 'FOOD',
  MIND = 'MIND',
  HABIT = 'HABIT',
}

/**
 * 미션 난이도
 */
export enum MissionDifficulty {
  EASY = 'EASY',
  NORMAL = 'NORMAL',
  CHALLENGE = 'CHALLENGE',
}

/**
 * 미션 템플릿 (정적 데이터)
 */
export interface MissionTemplate {
  id: string;
  category: MissionCategory;
  difficulty: MissionDifficulty;
  title: string;
  description: string;
  emoji: string;
  expReward: number; // 10~30
}

/**
 * 일일 미션 (할당된 미션)
 */
export interface DailyMission {
  templateId: string;
  category: MissionCategory;
  difficulty: MissionDifficulty;
  title: string;
  description: string;
  emoji: string;
  expReward: number;
  completed: boolean;
  completedAt?: string; // ISO timestamp
}

/**
 * 일일 미션 데이터
 */
export interface DailyMissionData {
  date: string; // YYYY-MM-DD
  missions: DailyMission[];
  allCompleted: boolean;
}

/**
 * 미션 히스토리 레코드
 */
export interface MissionHistoryRecord {
  date: string;
  missions: DailyMission[];
  allCompleted: boolean;
  fatiguePercentage: number;
}

/**
 * 스트릭 데이터
 */
export interface StreakData {
  currentStreak: number;
  longestStreak: number;
  lastCompletedDate: string; // YYYY-MM-DD
}

/**
 * 코스튬 해금 조건 타입
 */
export type CostumeUnlockCondition =
  | { type: 'level'; level: number }
  | { type: 'streak'; days: number }
  | { type: 'missions'; count: number }
  | { type: 'default' };

/**
 * 코스튬 희귀도
 */
export type CostumeRarity = 'common' | 'rare' | 'epic' | 'legendary';

/**
 * 코스튬 아이템
 */
export interface CostumeItem {
  id: string;
  name: string;
  emoji: string; // 코스튬 표현 이모지
  description: string;
  rarity: CostumeRarity;
  unlockCondition: CostumeUnlockCondition;
}

/**
 * 뿜 캐릭터 데이터
 */
export interface PpoomCharacterData {
  level: number;
  exp: number;
  equippedCostumeId: string | null;
  unlockedCostumeIds: string[];
}

/**
 * 뿜 통합 저장 구조
 */
export interface PpoomSaveData {
  character: PpoomCharacterData;
  streak: StreakData;
  missionHistory: MissionHistoryRecord[];
  currentMissions: DailyMissionData | null;
}
